COPY eleitorado (DT_GERACAO, HH_GERACAO, ANO_ELEICAO, SG_UF, CD_MUNICIPIO, NM_MUNICIPIO, CD_MUN_SIT_BIOMETRIA, DS_MUN_SIT_BIOMETRIA, NR_ZONA, CD_GENERO, DS_GENERO, CD_ESTADO_CIVIL, DS_ESTADO_CIVIL, CD_FAIXA_ETARIA, DS_FAIXA_ETARIA, CD_GRAU_ESCOLARIDADE, DS_GRAU_ESCOLARIDADE, QT_ELEITORES_PERFIL, QT_ELEITORES_BIOMETRIA, QT_ELEITORES_DEFICIENCIA, QT_ELEITORES_INC_NM_SOCIAL)
FROM 'C:\Program Files\PostgreSQL\15\bin\perfil_eleitorado_2020.csv'
DELIMITER ';'
CSV HEADER ENCODING 'LATIN1';