CREATE TABLE eleitorado(

	DT_GERACAO DATE,
	HH_GERACAO TIME,
	ANO_ELEICAO VARCHAR(10),
	SG_UF VARCHAR(2),
	CD_MUNICIPIO VARCHAR(10),
	NM_MUNICIPIO VARCHAR(50),
	CD_MUN_SIT_BIOMETRIA VARCHAR(2),
	DS_MUN_SIT_BIOMETRIA VARCHAR(50),
	NR_ZONA VARCHAR(5),
	CD_GENERO VARCHAR(2),
	DS_GENERO VARCHAR(25),
	CD_ESTADO_CIVIL VARCHAR(2),
	DS_ESTADO_CIVIL VARCHAR(25),
	CD_FAIXA_ETARIA VARCHAR(10),
	DS_FAIXA_ETARIA VARCHAR(20),
	CD_GRAU_ESCOLARIDADE VARCHAR(2),
	DS_GRAU_ESCOLARIDADE VARCHAR(50),
	QT_ELEITORES_PERFIL VARCHAR(5),
	QT_ELEITORES_BIOMETRIA VARCHAR(5),
	QT_ELEITORES_DEFICIENCIA VARCHAR(5),
	QT_ELEITORES_INC_NM_SOCIAL VARCHAR(5)

)